### ISSUE TITLE
Typo on Bayes Theorem?

### ISSUE THREAD

**Issue by davidheryanto** [ml874/Data-Science-Cheatsheet#1]
Hi, I was looking at the 1st page of your cheatsheet on Bayes Theorem. Is there a typo on the Bayes Theorem definition?
```
P(A|B) = P(B|A)P(B)/P(A)
```

I believe it should be
```
P(A|B) = P(B|A)P(A)/P(B)
```

https://en.wikipedia.org/wiki/Bayes%27_theorem

**Comment by ml874** [comment]
Good catch! Bayes has been corrected
